cpu : leon3mp
      generic map ( fabtech, memtech, padtech, clktech,
        disas, pclow )
      port map (
        resetn   => rst,
        clk      => clk,
        clk3     => clk3,
        pllref   => pllref,
        errorn   => errorn,
        wdogn    => wdogn,
        address  => address(27 downto 0),
        data     => data,
        ramsn    => ramsn,
        ramoen   => ramoen,
        rwen     => rwen,
        oen      => oen,
        writen   => writen,
        read     => read,
        iosn     => iosn,
        bexcn    => bexcn,
        brdyn    => brdyn,
        romsn    => romsn,
        sdclk    => sdclk,
        sdcsn    => sdcsn,
        sdwen    => sdwen,
        sdrasn   => sdrasn,
        sdcasn   => sdcasn,
        sddqm    => sddqm,
        dsuen    => dsuen,
        dsubre   => dsubre,
        dsuact   => dsuact,
        txd1     => txd1,
        rxd1     => rxd1,
        ctsn1    => ctsn1,
        rtsn1    => rtsn1,
        txd2     => txd2,
        rxd2     => rxd2,
        ctsn2    => ctsn2,
        rtsn2    => rtsn2,
        pio      => pio,

        -- Internal grethm (CFG_GRETH=1) is still active inside leon3mp.
        -- These are its top-level PHY pins. Tying them off here only
        -- disconnects the PHY side -- it does NOT disable the internal
        -- AHB/APB GRETH core itself. emdio is inout so it must be 'Z',
        -- not open and not '0' (driving an inout to a constant from
        -- outside fights any internal driver).
        emdio    => open,
        etx_clk  => '0',
        erx_clk  => '0',
        erxd     => "0000",
        erx_dv   => '0',
        erx_er   => '0',
        erx_col  => '0',
        erx_crs  => '0',
        emdint   => '0',
        etxd     => open,
        etx_en   => open,
        etx_er   => open,
        emdc     => open,

        ps2clk   => ps2clk,
        ps2data  => ps2data,
        vid_clock  => vid_clock,
        vid_blankn => vid_blankn,
        vid_syncn  => vid_syncn,
        vid_hsync  => vid_hsync,
        vid_vsync  => vid_vsync,
        vid_r      => vid_r,
        vid_g      => vid_g,
        vid_b      => vid_b,
        spw_clk    => spw_clk,
        spw_rxdp   => spw_rxdp,
        spw_rxdn   => spw_rxdn,
        spw_rxsp   => spw_rxsp,
        spw_rxsn   => spw_rxsn,
        spw_txdp   => spw_txdp,
        spw_txdn   => spw_txdn,
        spw_txsp   => spw_txsp,
        spw_txsn   => spw_txsn,
        usb_clkout    => usb_clkout,
        usb_d         => usb_d,
        usb_linestate => usb_linestate,
        usb_opmode    => usb_opmode,
        usb_reset     => usb_reset,
        usb_rxactive  => usb_rxactive,
        usb_rxerror   => usb_rxerror,
        usb_rxvalid   => usb_rxvalid,
        usb_suspend   => usb_suspend,
        usb_termsel   => usb_termsel,
        usb_txready   => usb_txready,
        usb_txvalid   => usb_txvalid,
        usb_validh    => usb_validh,
        usb_xcvrsel   => usb_xcvrsel,
        usb_vbus      => usb_vbus
      );
